### ISSUE TITLE
Implement the /series/:id endpoint

### ISSUE THREAD

**Issue by KenavR** [DevvitIO/Lanflix#24]
> Dependencies: 
>- [ ] back-end: specification of the endpoint (#4)

Generally /series/:id ~~(/:name)~~ (GET) returns the series with the specified ID (:id param) from the database.

**Comment by ozgunbal** [comment]
i didn't get to (/:name) part exactly. Is it only get name of the related series rather than object of it?

**Comment by KenavR** [comment]
It arguably just makes the URL nicer to read. An Example for that is StackOverflow's _/users/:id/:username_ url. In my opinion _/series/3/Stranger-Things_ is nicer than just _/series/3_, but you only need the id to retrieve the object from the database. 

**Anyway, this was a mistake on my part. Since this isn't the URL the user sees _/series/:id_ is certainly enough and the name could just be used on the front-end routing.**
