### ISSUE TITLE
Implement the /series/:id/episodes/:eid endpoint

### ISSUE THREAD

**Issue by KenavR** [DevvitIO/Lanflix#26]
> Dependencies: 
> 
> - [ ] back-end: specification of the endpoint (#7)

Generally /series/:id/episodes/:eid (GET) returns the episode with the specified ID (:eid param) of the series with the specified ID (:id param) from the database.

**Comment by ozgunbal** [comment]
@KenavR I'll wait your update to #6 . Then, i'll start this issue.

**Comment by KenavR** [comment]
@ozgunbal I have updated the models. Hope that helps.
