### ISSUE TITLE
Implement the /movies endpoint

### ISSUE THREAD

**Issue by KenavR** [DevvitIO/Lanflix#27]
> Dependencies: 
> 
> - [ ] back-end: specification of the endpoint (#7)

Generally /movies (GET) returns the entire list of movies from the database.

**Comment by blb451** [comment]
I'd love to take care of this.

**Comment by KenavR** [comment]
Great. Sadly I didn't have time so far to define the endpoint or the model, but I will add it today or tomorrow. Anyhow, I think you could implement the basic structure now, with just a movie name. 

I would just make one suggestion, move the logic that loads the movies from the database into a "MovieService" or something, so people can use it for other endpoints (e.g. /browse) and we are able to maybe extend it with filters, limits or offset in the future.

**Comment by blb451** [comment]
Ah, that's alright! I kinda just saw the task and took a quick glance last
night. Let me take my name off of it for now and I'll come back and check
things out in a few days!


Thanks for getting back to me,

Benjamin.

**Comment by AndrewMusgrave** [comment]
Was this assigned to anyone?

**Comment by KenavR** [comment]
No, it wasn't, the person deleted their comments and said they would come back later. If you'd like to work on it, it would be appreciated. I won't be able to update the models today. I am at work until 9 pm and I have the first part of a paper due today. I promise I will update them tomorrow.

**Comment by AndrewMusgrave** [comment]
Sure I'll start it now.

> I would just make one suggestion, move the logic that loads the movies from the database into a "MovieService" or something, so people can use it for other endpoints (e.g. /browse) and we are able to maybe extend it with filters, limits or offset in the future.

I'll purpose a slight change in the controller structure that might make this a little easier. I'll change it and put in a PR in a couple minutes. Let me know what you think when you have time.

**Comment by KenavR** [comment]
I wrote my feedback in the PR.
