### ISSUE TITLE
Add livereload

### ISSUE THREAD

**Issue by KenavR** [DevvitIO/Lanflix#32]
I tried to keep it as simple as possible but now noticed the limitations. Currently, the server restarts whenever something changes (nodemon) but the browser doesn't automatically refresh the page. I will certainly fix that in the future, but if someone else wants to do it, go for it.

**Comment by teevik** [comment]
Hey could perhaps add this? https://www.npmjs.com/package/reload

Could also do something like this https://stackoverflow.com/a/15574722 so it will automatically include the client side script when running on development environment
