### ISSUE TITLE
[Title-Card] Remove unchangeable structure from title-card definition

### ISSUE THREAD

**Issue by KenavR** [DevvitIO/Lanflix#35]
> This is an "improvement" to the title-card implemented in issue #9.

Currently, if a user wants to use a title-card it looks something like this

```html
<div class="lf-title-card"><br />
    <i class="lf-play-btn fa fa-play-circle-o" aria-hidden="true"></i><br />
    <div class="lf-title">Rick and Morty</div><br />
    <img class="lf-cover" src="image_source"><br />
</div>
```

The following part always looks the same.
```html
<i class="lf-play-btn fa fa-play-circle-o" aria-hidden="true"></i><br />
```

Rather than forcing the user to always add it to the component, I suggest adding it in Javascript. The general suggestion of reducing the component's definition to a minimum applies to other things as well. 
Maybe look into, how you may also reduce the rest of the code.

@WebDevMR Maybe you want to look into Javascript or anyone else is welcome.

### Javascript function you may need
[Document.createElement()](https://developer.mozilla.org/de/docs/Web/API/Document/createElement)
[Document.getElementsByClassName()](https://developer.mozilla.org/de/docs/Web/API/Document/getElementsByClassName)
[ParentNode.prepend()](https://developer.mozilla.org/de/docs/Web/API/ParentNode/prepend)

[Create Element from String](https://stackoverflow.com/questions/494143/creating-a-new-dom-element-from-an-html-string-using-built-in-dom-methods-or-pro)

**Comment by teevik** [comment]
Hey, is it ok if i work on this?

**Comment by KenavR** [comment]
Sure that would be great. Just as a side note the current card looks a little bit different than described above. #37 implemented the default cover and changed the structure a little bit. It looks something like 

```html
<div class="lf-title-card">
    <i class="lf-play-btn fa fa-play-circle-o" aria-hidden="true"></i>
    <div class="lf-title">Rick and Morty</div>
    <img src="https://static.tvmaze.com/uploads/images/medium_portrait/1/3603.jpg" onerror="if (this.src != 'components/title-card/default.png') this.src = 'components/title-card/default.png';"/>
</div>
```

The end result for people who use the component should look something like

```html
<div class="lf-title-card">
    <div class="lf-title">Rick and Morty</div>
    <img src="https://static.tvmaze.com/uploads/images/medium_portrait/1/3603.jpg" />
</div>
```

If you want to [join](https://orgmanager.miguelpiedrafita.com/join/32555830) the organisation I can assign the issue to you.

**Comment by teevik** [comment]
Alright, joined the organisation
