### ISSUE TITLE
Update Models

### ISSUE THREAD

**Issue by KenavR** [DevvitIO/Lanflix#48]
#6 should define the needed models.

**Comment by ozgunbal** [comment]
I'm on it.

**Comment by howtogetamericannetflix** [comment]
<a href="https://www.w3schools.com">Visit W3Schools</a>
Try it Yourself »

**Comment by NemanjaMilosevic** [comment]
@KenavR you should close this issue.

**Comment by KenavR** [comment]
@NemanjaMilosevic You are right, thank you.
