### ISSUE TITLE
Series/Movie Title Card

### ISSUE THREAD

**Issue by KenavR** [DevvitIO/Lanflix#9]
Create a .lf-title-card component that shows the cover image, the name of the movie/series (e.g. [tvmaze source](https://static.tvmaze.com/uploads/images/medium_portrait/1/3603.jpg)) and has some hover effect. If there is no image provided, the component should show a default image. We can discuss if there should be additional information on the card, but my suggestion is to keep it in a separate popover to a) not clutter the UI and b) allow someone else to implement the popover.

![image](https://user-images.githubusercontent.com/6655009/31608324-48fc1666-b270-11e7-8df9-84173bcd90a1.png)

The result could look something like this, but you certainly have some creative freedom. 

### Additional info:
For the play icon and other icons, I suggest using [fontawesome](http://fontawesome.io/icons/) . If it isn’t already added, please add the CDN link in the index.html file. 

A component could consist of multiple classes. Since the user of the component needs to be able to provide the source of the image and the title the basic structure to use it may look something like this:

```html
<div class=”lf-title-card”>
  <img class=”lf-cover” src=”...”>
  <div class=”lf-title”>...</div>
</div> 
```

Anyway, don’t force the user to add more than necessary.

**Comment by WebDevMR** [comment]
How should this be structured in the project? Should there be a title-card directory in the components folder which contains the css for the component? And then the html for it in the components-playground/index.html?

**Comment by KenavR** [comment]
If the component itself needs additional HTML (which is injected by Javascript) it should be part of the component (title-card) directory. 

e.g. if that
```html
<div class=”lf-title-card”>
  <img class=”lf-cover” src=”...”>
  <div class=”lf-title”>...</div>
</div>
``` 
is what the user needs to write to get the component, but the actually structure of the component looks something like

```html
<div class=”lf-title-card”>
  <img class=”lf-cover” src=”...”>
  <div class=”lf-title”>...</div>
  <!-- This line is new -->
  <div class="lf-card-overlay"></div>
</div>
``` 
there most likly needs to be some additional HTML or at least some Javascript to modify the structure of the resulting HTML code.

The playground is just a way to test out your component and give people a place to browse the available components. 

I may write a more detailed tutorial.

**Comment by WebDevMR** [comment]
Can you assign this to me?
